events {}

http {
    
    upstream backend-pool {
        server backend1;
        server backend2;
        server backend3;
    }
    
    server {
        listen 80;

        location / {
            proxy_pass http://backend-pool/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
#From Stage 2, Session 2.2: Load Balance Across Several Backends
