events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://my-backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}

#From Stage 2, Session 2.1: Proxy One Backend With Nginx
